### PR TITLE
Feature/environment granularity

### PR DESCRIPTION
**Pull request by DavoCoder**

### CODE REVIEW

**Review by olamiral-mulesoft — COMMENTED** [review]
- Environment details for Runtime Fabric are consistent with environment type summary section

- **apiManagerMetrics.apis**
The following stats exist in summary section but are missing in env detail section:
  - total (managedApisTotal? If yes, should be rename to total to keep consistency with summary section)
  - active
  - inactive
  - contracts
  - automatedPoliciesUsed
  - automatedPoliciesUsedTotal
  - transactions

- **runtimeManagerMetrics.hybrid**
The following stats exist in summary section but are missing in env detail section:
  - servers
  - clusters
  - serverGroups
  - runtimeUsed
  - runtimeTotal

**Comment by damiancalabresi** [comment]
@olamiral-mulesoft 
Regarding API Manager metrics, as far as I can see, the existing ones: 

total, active, inactive, contracts, etc

Didn't identify if the metric was about APIs or API Instances. This is what David fixed in the environment metrics, where most of them have the prefix "apiInstances". He didn't change the existing ones for backward compatibility.

**Comment by damiancalabresi** [comment]
I see the contracts and transactions metric is still missing in the environment details, but I think those metrics add no value, it's ok to ignore them.

About ARM, I'm adding servers, clusters, and serverGroups. **runtimeUsed** is not a metric, I agree with the idea of not including it in the details section.

**Comment by olamiral-mulesoft** [comment]
> @olamiral-mulesoft
> Regarding API Manager metrics, as far as I can see, the existing ones:
> 
> total, active, inactive, contracts, etc
> 
> Didn't identify if the metric was about APIs or API Instances. This is what David fixed in the environment metrics, where most of them have the prefix "apiInstances". He didn't change the existing ones for backward compatibility.

@damiancalabresi 
Make sense. As users can get confused due to the the naming convention changes in API Manager metrics (summary vs details), maybe it would be nice to add a note in the readme explaining how details stats relate to summary stats for API Manager Metrics (users will ask questions about it and we can point them to the readme file):  
- _managedApisTotal_: corresponds to _total_ 
- _apiInstancesActive_: corresponds to _active_
- _apiInstancesInactive_: corresponds to _inactive_
- _apiInstancesTotal_: corresponds to _apiInstances_
- _apiInstancesWithContract_: corresponds to _contracts_
- _apiInstancesWith*_: corresponds to _apisWith*_

**Comment by olamiral-mulesoft** [comment]
> I see the contracts and transactions metric is still missing in the environment details, but I think those metrics add no value, it's ok to ignore them.
> 
> About ARM, I'm adding servers, clusters, and serverGroups. **runtimeUsed** is not a metric, I agree with the idea of not including it in the details section.

I understand your point, but if we have a metric in the summary the we should add them to the details too, and let the customer decide if they want to use it or not. Anyway, I agree that they might not be that relevant, but I'd let that decision with the customer.

Regarding **runtimeUsed**, my point is that we should be consistent: for rtf and ch, the details section contains the list of runtimes used. We have 2 options: 1) remove runtimesUsed from rtf and ch; 2) add it to hybrid. 
**Note**: runtimesUsedTotal in summary does not correspond to the sum of runtimesUsedTotal in each environment (the total of runtimes in summary corresponds to the number of runtimes contained in the union of the set of runtimes used in each environment).

**Comment by damiancalabresi** [comment]
I added server, cluster and serverGroups by environment.

Request to get Cluster was incorrectly mocked, I fixed the test and the results.

I validated all the new metrics except for the Anypoint MQ ones. @melamedjoel Could you validate them?

**Comment by melamedjoel** [comment]
Checked and perfectly fine. I approve as well the PR and we are able to merge @damiancalabresi

**Review by melamedjoel — APPROVED** [review]
Checked and tested. Approved

**Comment by DavoCoder** [comment]
@olamiral-mulesoft Thanks for all the comments and observations, I have updated all metrics: 1) To have 100% consistency with the aggregated metric-names. 2) Included missing metrics on the "details" nodes, for API Manager and Hybrid. Updated unit tests and tested this with accounts that have RTF/CH/Standalone

**Review by melamedjoel — APPROVED** [review]
Tested in CH and double-check MQ data. Everything seems OK. Also, looks good to me the latest changes to include transactions and other types of data in the environments information, and consistency between granular and non-granular fields

**Review by olamiral-mulesoft — APPROVED** [review]
- RTF stats are consistent (run against an account having RTF)
- API Manager stats consistent (summary vs details)
- Runtime manager metrics consistent across all deployment models (metrics and summary vs details)

**Comment by panizzag** [comment]
Hybrid changes are working as expected. The granularity by environment type seems to be working fine:

image

**Review by damiancalabresi — APPROVED** [review]
Validated on Customer organization, everything seems to be correct

**Pull request merged**
